<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3035" started-at="2018-11-16T04:43:23Z" finished-at="2018-11-16T04:43:27Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="3035" started-at="2018-11-16T04:43:23Z" finished-at="2018-11-16T04:43:27Z">
      <class name="API_Framework.API_Framework.Test1">
        <test-method status="PASS" signature="testB()[pri:0, instance:API_Framework.API_Framework.Test1@192c3f1e]" name="testB" is-config="true" duration-ms="38" started-at="2018-11-16T10:13:23Z" finished-at="2018-11-16T10:13:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB -->
        <test-method status="FAIL" signature="test1()[pri:0, instance:API_Framework.API_Framework.Test1@192c3f1e]" name="test1" duration-ms="3008" started-at="2018-11-16T10:13:24Z" finished-at="2018-11-16T10:13:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	author matched expected [43] but found [typicode],
	Title matched expected [43-server] but found [json-server]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	author matched expected [43] but found [typicode],
	Title matched expected [43-server] but found [json-server]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at API_Framework.API_Framework.Test1.test1(Test1.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- API_Framework.API_Framework.Test1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
